---
abstract: 'AnyEvent::HTTP wrapper'
author:
  - 'Hyungsuk Hong <hshong@perl.kr>'
build_requires:
  AnyEvent: 0
  Test::More: 0
  strict: 0
  utf8: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-HTTP-ScopedClient
requires:
  AnyEvent::HTTP: 0
  Encode: 0
  HTTP::Request: 0
  MIME::Base64: 0
  Moose: 0
  Try::Tiny: 0
  URI: 0
  URI::Escape: 0
  URI::QueryParam: 0
  namespace::autoclean: 0
version: 0.0.5
